baseURL: /
languageCode: id-id
title: Annas Dwi
theme: "papermod"

params:
  env: production
  homeInfoParams:
    Title: Hi there 👋
    Content: Nulis apa yang kusuka
  socialIcons:
    - name: "github"
      url: "https://www.github.com/anasdwc"
    - name: "twitter"
      url: "https://www.twitter.com/anasdwc"
    - name: "linkedin"
      ulr: "https://linkedin.com/in/anasdwc"
  ShowReadingTime: true
  ShowToc: true
  ShowCodeCopyButtons: true
  author: "Annas Dwi"

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives
      weight: 10
